apiVersion: v1
kind: Service
metadata:
  name: {{ include "database-operator.name" . }}
  labels:
    {{- include "database-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: default
  selector:
    {{- include "database-operator.selectorLabels" . | nindent 4 }}
